//Meetups Data Getting
export const GET_MEETUPS_LOADING = 'GET_MEETUPS_LOADING';
export const GET_MEETUPS_SUCCESS = 'GET_MEETUPS_SUCCESS';
export const GET_MEETUPS_ERROR = 'GET_MEETUPS_ERROR';

//Login - Auth check
export const GET_AUTH_LOADING = 'GET_AUTH_LOADING';
export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
export const GET_AUTH_ERROR = 'GET_AUTH_ERROR';

//Register
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
